### ISSUE TITLE
Bridge keeps crashing on Kraken Elite v2: `AssertionError: missing messages (attempts=50, missing=1)`

### ISSUE THREAD

**Issue by fu-raz** [brokenmass/KrakenLCDPlayground#16]
Is there a way for me to log what's going on? Or should I try the python script and see if there are exceptions?

**Comment by fu-raz** [comment]
So I ran the python version to see when and where it would crash:

```
Exception in thread FrameWriter:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2032.0_x64__qbz5n2kfra8p0\Lib\threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "D:\AIOLCDUnchained\workers.py", line 27, in run
    self.onFrame()
  File "D:\AIOLCDUnchained\signalrgb.py", line 385, in onFrame
    super().onFrame()
  File "D:\AIOLCDUnchained\workers.py", line 33, in onFrame
    self.lcd.writeFrame(frame)
  File "D:\AIOLCDUnchained\driver.py", line 419, in writeFrame
    result = self.writeQ565(frame)
             ^^^^^^^^^^^^^^^^^^^^^
  File "D:\AIOLCDUnchained\driver.py", line 388, in writeQ565
    status = self.readUntil({b"\x37\x02": self.parseStandardResult})
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AIOLCDUnchained\driver.py", line 195, in readUntil
    False
AssertionError: missing messages (attempts=50, missing=1)
```

**Comment by brokenmass** [comment]
Is CAM definitely closed ? Any other tool that might use the serial port to communicate to the pump ?

**Comment by fu-raz** [comment]
Yes cam is closed. I'm using SignalRGB. It might be SRGB's fan control? But that would be very unfortunate, cause it would make me choose between fan control or LCD screen hahah. I'm using their latest updated plugin:

https://gitlab.com/signalrgb/signal-plugins/-/blob/Development/Plugins/Nzxt/NZXT_Kraken_Elite_V2_AIO.js?ref_type=heads

I don't know if they use the serial port for fan control though, or if that's done via the HID device.

**Comment by brokenmass** [comment]
Ok I see. Can you disable srgb fan control and let me know if lcd works ? If that’s the case I can submit a patch to the kraken plugin (I think the one for the old kraken they are using the one that was written by me)

Looking at the code it seems like the plugin is the culprit (the poll status is consuming the WHOLE serial buffer, even packets that it should ignore.

**Comment by fu-raz** [comment]
I think that's it! Last time it would only run for a minute and then crash, now it's been running for a whole lot longer and it's still going!

Dordo would probably be very happy if you could fix it. From what I heard, he has a lot of devices still waiting for him haha!
